name: Build
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get flex 💪 and bison 🦬
        run: |
          sudo apt install flex bison

      - name: Make 🔧
        run: |
          make

      - name: Test 🚀
        run: |
          make test
